export var POPPINS={
    PoppinsBlack:"Poppins-Black",
    PoppinsBlackItalic:"Poppins-BlackItalic",
    PoppinsBold:"Poppins-Bold",
    PoppinsExtraBold:"Poppins-ExtraBold",
    PoppinsBoldItalic:"Poppins-BoldItalic",
    PoppinsExtraBoldItalic:"Poppins-ExtraBoldItalic",
    PoppinsExtraLight:"Poppins-ExtraLight",
    PoppinsItalic:"Poppins-Italic",
    PoppinsLight:"Poppins-Light",
    PoppinsLightItalic:"Poppins-LightItalic",
    PoppinsMedium:"Poppins-Medium",
    PoppinsMediumItalic:"Poppins-MediumItalic",
    PoppinsRegular:"Poppins-Regular",
    PoppinsSemiBold:"Poppins-SemiBold",
    PoppinsSemiBoldItalic:"Poppins-SemiBoldItalic",
    PoppinsThin:"Poppins-Thin",
}

export var ROBOTO={
    RobotoBlack:"Roboto-Black",
    RobotoBlackItalic:"Roboto-BlackItalic",
    RobotoBold:"Roboto-Bold",
    RobotoExtraBold:"Roboto-ExtraBold",
    RobotoBoldItalic:"Roboto-BoldItalic",
    RobotoExtraBoldItalic:"Roboto-ExtraBoldItalic",
    RobotoExtraLight:"Roboto-ExtraLight",
    RobotoItalic:"Roboto-Italic",
    RobotoLight:"Roboto-Light",
    RobotoLightItalic:"Roboto-LightItalic",
    RobotoMedium:"Roboto-Medium",
    RobotoMediumItalic:"Roboto-MediumItalic",
    RobotoRegular:"Roboto-Regular",
    RobotoSemiBold:"Roboto-SemiBold",
    RobotoSemiBoldItalic:"Roboto-SemiBoldItalic",
    RobotoThin:"Roboto-Thin",
}